config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'post_images#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :post_images, only: [:new, :create, :index, :show] do
  	resource :favorites, only: [:create, :destroy]
  	resource :post_comments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :configure_permitted_parameters, if: :devise_controller?
protected
def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end

class ApplicationController < ActionController::Base
	before_action :authenticate_user!

app/controllers/post_commnets_controller.rb
class PostCommnetsController < ApplicationController
	def create
		post_image = PostImage.find(params[:post_image_id])
		comment = current_user.post_comments.new(post_comment_params)
		comment.post_image_id = post_image.post_image_id
		comment.save
		redirect_to post_image_path(post_image)
	end
	private
	def post_comment_params
		params.require(:post_comment).permit(:user_id, :post_image_id, :comment)
		
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
	def new
		@post_image = PostImage.new
	end

	def create
		@post_image = PostImage.new(post_image_params)
		@post_image.user_id = currenr_user.id
		@post_image.save
		redirect_to post_images_path
	end

	def index
		@post_images = PostImages.all
	end
	def show
		@post_image = PostImage.find(params[:id])
		@post_comment = PostComment.new
	end
	private
	def post_image_params
		params.require(:post_image).permit(:shop_name, :image, :caption)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_commnets_helper.rb
module PostCommnetsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meshiterro</title>
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,600,700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  </head> 

  <body>

    <div class="header" id="header">
      <nav class="navbar navbar-main navbar-shadow" role="navigation" id="slide-nav">
        <div class="container relative">
          <div class="navbar-header">
            <a class="navbar-logo" href="/">
              <%= image_tag('logo.png') %>
            </a>
   
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div id="slidemenu">
            <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
              <% if user_signed_in? %>
	      	  	<li class="">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
              </li>
              <li class="">
                <%= link_to '投稿フォーム', new_post_image_path %>
              </li>
              <li class="">
                <%= link_to "新規投稿", new_user_regisration_path %>
              </li>
              <li class="">
                <%= link_to "ログイン", new_user_session_path %>
              </li>
              <% end %>
            </ul>
          </div>

          
                <a href="">
                  <span>新規登録</span>
                </a>
              </li>
              <li class="">
                <a href="">
                  <span>ログイン</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  
    <%= yield %>

   <footer class="footer style-2">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="col">
              <br>
              <p class="no-margin" style="font-size: 11px;">
              <br>
              善良な市民同士で無差別に食欲を煽るSNS
          </p>
              <%= image_tag('logo-white.png') %>
              
            </div>
          </div>
          <div class="col-md-2">
            <div class="col">
              <h4>Link</h4>
              <ul>
                <li>
                  <a href="" title="About">会社概要</a>
                </li>
                <li>
                  <a href="" title="License informations">プライバシーポリシー</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>

app/views/post_images/index.html.erb
<section class="sct-color-1 slice">
	<div class="container-fluid masonry-container">
		<div class="row">
			<div class="col-md-8" col-sm-offset-2>
				<div class="maeonry-wrapper-cols">
					<div class="masonry-gutter"></div>
					<% @post_images.each do |post_image| %>
					<div class="masonry-block">
						<div class="block block-image vl">
							<div class="block-image">
								<div class="view view-first">
									<%= attachment_image_tag post_image, :image %>
								</div>
							</div>
							<div class="block-content">
								<%= image_tag('sample-authorl.jpg', class: "img-circle pull-left profile-thmb") %>
								<h3 class="block-title">
									<%= link_to post_image_path(post_image.id) do %>
									<i class="fa fa-map-marker"></i><%= post_image.shop_name %>
									<% end %>
								</h3>
								<p><%= post_image.caption %></p>
								<ul class="inline-meta">
									<li>By
										<%= post_image.user.name %>
									</li>
									<li>
										<a href="#">23 コメント</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/post_images/new.html.erb
<%= form_for(@post_image, url: post_images_path) do |f| %>
  <% if @post_image.errors.any? %>
    <div id="error_explanation">
    <h2><%= @post_image.errors.count %>件のエラーが発生しました。</h2>
    <ul>
    <% @post_imagge.errors.full_messages.each do |messages| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<div class="row">
	<div class="col-sm-12">
		<%= f.attachment_fiels :image %>
	</div>
</div>
<br>
<div class="row">
	<div class="col-sm 6">
		<div class="form-group has-icon">
			<lanel class="control-label sr-only">ショップ名</lanel>
			<%= f.text_field :shop_name, class:"form-control", placeholder:"ショップ名" %>
			<span class="fa fa-building form-control-icon" aria-hidden="true"></span>
		</div>
	</div>
	<div class="col-sm-6">
	</div>
</div>
<div class ="row">
	<div class="col-sm-12">
		<%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
	</div>
</div>
<hr>
<%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

app/views/post_images/show.html.erb
<div class="post-meta-top">
	<div class="post-image">
		<%= attachment_image_tag @post_image, :image %>
	</div>
</div>
<div class="post-content">
	<h2 class="post-title"><%= @post_image.shop_name %></h2>
	<ul class="meta-info-cells v4 float-wrapper">
		<li>
			<i class="fa fa-user"></i>By<a href="#">
				<%= @post_image.user.name %></a>
			</li>
			<li>
				<i class="fa fa-calendar"></i><%= @post_image.created_at.strftime('%Y/%m/%d') %>
			</li>
			<li>
				<i class="fa fa-heart"></i>
				<a href="#">202 いいね</a>
			</li>
			<li>
				<i class="fa fa-commnet"></i>
				<a href="#comments">4</a>
			</li>
		</ul>
		<div class="post-content-inner mt-20">
			<p><%= @post_image.caption %></p>
		</div>
	</div>